# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headImg',
            field=models.FileField(default='activity/static/01.jpg', upload_to='activity/static/'),
        ),
    ]
