# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20160726_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=3),
        ),
    ]
